// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEpkOf12Xy4aGTGd4zKsIUZ-aaEJfEtGk',
    appId: '1:410315482061:web:aa3364e9a1677e6a0b9a84',
    messagingSenderId: '410315482061',
    projectId: 'wallpaper-8cc23',
    authDomain: 'wallpaper-8cc23.firebaseapp.com',
    databaseURL: 'https://wallpaper-8cc23-default-rtdb.firebaseio.com',
    storageBucket: 'wallpaper-8cc23.appspot.com',
    measurementId: 'G-GFLMZKCKX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPgzN9UO_U4jHOnAPpZjbdRItAlXQAbnU',
    appId: '1:410315482061:android:0a68ae0ba8ac7cb60b9a84',
    messagingSenderId: '410315482061',
    projectId: 'wallpaper-8cc23',
    databaseURL: 'https://wallpaper-8cc23-default-rtdb.firebaseio.com',
    storageBucket: 'wallpaper-8cc23.appspot.com',
  );
}
